export interface OrderProductItem {
    id: string;
    name: string;
    brand: string;
    price: number;
    quantity: string;
    subtotal: number;
    image: string;
}

export type OrderProgressStatus =
    | "Order Placed"
    | "Order Confirmed"
    | "InTransit"
    | "Delivered"
    | "Failed";

export type OrderCategory = "ongoing" | "completed" | "failed";

export interface OrderRecord {
    id: string;
    orderNumber: string;
    customerName: string;
    customerEmail: string;
    customerPhone: string;
    deliveryAddress: string;
    amount: number;
    subtotal: number;
    deliveryFee: number;
    progress: OrderProgressStatus;
    category: OrderCategory;
    date: string;
    placedAt: string;
    confirmedAt?: string;
    inTransitAt?: string;
    deliveredAt?: string;
    failedAt?: string;
    paymentStatus: "Completed" | "Pending" | "Failed";
    items: OrderProductItem[];
}

export const sampleOrderItems: OrderProductItem[] = [
    {
        id: "1",
        name: "Glenfiddich Single Scotch",
        brand: "Glenfiddich",
        price: 75000,
        quantity: "2 Pieces",
        subtotal: 150000,
        image: "https://res.cloudinary.com/dzk1a6bjt/image/upload/v1784813212/p_5_ohp3t7.png",
    },
    {
        id: "2",
        name: "Hennessy XO",
        brand: "Hennessy",
        price: 242000,
        quantity: "10 Cases",
        subtotal: 3125000,
        image: "https://res.cloudinary.com/dzk1a6bjt/image/upload/v1784803007/Image_2_xcjlsy.png",
    },
    {
        id: "3",
        name: "Don Julio 1942",
        brand: "Don Julio",
        price: 60000,
        quantity: "6 Pieces • 10 Cases",
        subtotal: 320000,
        image: "https://res.cloudinary.com/dzk1a6bjt/image/upload/v1784813213/p_1_pndwco.png",
    },
];

export const initialOrdersList: OrderRecord[] = [
    // Ongoing Orders
    {
        id: "1",
        orderNumber: "RE-2026-7890",
        customerName: "John Amadi",
        customerEmail: "J.amadi1@gmail.com",
        customerPhone: "091 2345 6789",
        deliveryAddress: "16 Pinnock Beach Rd, Lekki Phase 1, Lagos",
        amount: 75000,
        subtotal: 75000,
        deliveryFee: 0,
        progress: "InTransit",
        category: "ongoing",
        date: "25th July, 2024",
        placedAt: "29 July 2026 at 10:42PM",
        confirmedAt: "29 July 2026 at 10:42PM",
        inTransitAt: "29 July 2026 at 10:42PM",
        paymentStatus: "Completed",
        items: sampleOrderItems,
    },
    {
        id: "2",
        orderNumber: "RE-2026-7892",
        customerName: "Quilox Ent",
        customerEmail: "vip@quilox.ng",
        customerPhone: "080 9999 1234",
        deliveryAddress: "Ozumba Mbadiwe Ave, Victoria Island, Lagos",
        amount: 3125000,
        subtotal: 3125000,
        deliveryFee: 0,
        progress: "InTransit",
        category: "ongoing",
        date: "26th July, 2024",
        placedAt: "26 July 2024 at 02:15PM",
        confirmedAt: "26 July 2024 at 03:00PM",
        inTransitAt: "26 July 2024 at 04:30PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[1]],
    },
    {
        id: "3",
        orderNumber: "RE-2026-7891",
        customerName: "Castiel Dean",
        customerEmail: "castiel@winchester.com",
        customerPhone: "081 2233 4455",
        deliveryAddress: "Banana Island, Ikoyi, Lagos",
        amount: 120000,
        subtotal: 120000,
        deliveryFee: 0,
        progress: "Order Confirmed",
        category: "ongoing",
        date: "27th July, 2024",
        placedAt: "27 July 2024 at 11:20AM",
        confirmedAt: "27 July 2024 at 12:05PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0]],
    },
    {
        id: "4",
        orderNumber: "RE-2026-7890",
        customerName: "Castle Lounge",
        customerEmail: "reservations@castlelounge.com",
        customerPhone: "070 3344 5566",
        deliveryAddress: "Admiralty Way, Lekki Phase 1, Lagos",
        amount: 5000000,
        subtotal: 5000000,
        deliveryFee: 0,
        progress: "InTransit",
        category: "ongoing",
        date: "25th July, 2024",
        placedAt: "25 July 2024 at 09:30AM",
        confirmedAt: "25 July 2024 at 10:15AM",
        inTransitAt: "25 July 2024 at 01:00PM",
        paymentStatus: "Completed",
        items: sampleOrderItems,
    },
    {
        id: "5",
        orderNumber: "RE-2026-7893",
        customerName: "Sunflower Bar",
        customerEmail: "orders@sunflowerbar.ng",
        customerPhone: "080 5566 7788",
        deliveryAddress: "Bourdillon Rd, Ikoyi, Lagos",
        amount: 1225000,
        subtotal: 1225000,
        deliveryFee: 0,
        progress: "Order Confirmed",
        category: "ongoing",
        date: "28th July, 2024",
        placedAt: "28 July 2024 at 01:10PM",
        confirmedAt: "28 July 2024 at 02:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[2]],
    },
    {
        id: "6",
        orderNumber: "RE-2026-7897",
        customerName: "Daisy Dine",
        customerEmail: "chef@daisydine.ng",
        customerPhone: "090 1122 3344",
        deliveryAddress: "Adeola Odeku St, Victoria Island, Lagos",
        amount: 1350000,
        subtotal: 1350000,
        deliveryFee: 0,
        progress: "InTransit",
        category: "ongoing",
        date: "29th July, 2024",
        placedAt: "29 July 2024 at 11:00AM",
        confirmedAt: "29 July 2024 at 11:45AM",
        inTransitAt: "29 July 2024 at 02:30PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0], sampleOrderItems[2]],
    },
    {
        id: "7",
        orderNumber: "RE-2026-7893",
        customerName: "Sunflower Bar",
        customerEmail: "orders@sunflowerbar.ng",
        customerPhone: "080 5566 7788",
        deliveryAddress: "Bourdillon Rd, Ikoyi, Lagos",
        amount: 1475000,
        subtotal: 1475000,
        deliveryFee: 0,
        progress: "Order Confirmed",
        category: "ongoing",
        date: "30th July, 2024",
        placedAt: "30 July 2024 at 04:15PM",
        confirmedAt: "30 July 2024 at 05:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[1]],
    },
    {
        id: "8",
        orderNumber: "RE-2026-7896",
        customerName: "Rosemary Bistro",
        customerEmail: "bar@rosemarybistro.com",
        customerPhone: "081 7788 9900",
        deliveryAddress: "Sanusi Fafunwa St, Victoria Island, Lagos",
        amount: 1600000,
        subtotal: 1600000,
        deliveryFee: 0,
        progress: "InTransit",
        category: "ongoing",
        date: "31st July, 2024",
        placedAt: "31 July 2024 at 10:00AM",
        confirmedAt: "31 July 2024 at 10:45AM",
        inTransitAt: "31 July 2024 at 01:20PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0], sampleOrderItems[1]],
    },
    {
        id: "9",
        orderNumber: "RE-2026-7894",
        customerName: "Lavender Lounge",
        customerEmail: "manager@lavenderlounge.ng",
        customerPhone: "080 6677 8899",
        deliveryAddress: "Bisola Durosinmi Etti Dr, Lekki Phase 1, Lagos",
        amount: 1725000,
        subtotal: 1725000,
        deliveryFee: 0,
        progress: "Order Confirmed",
        category: "ongoing",
        date: "1st August, 2024",
        placedAt: "1 August 2024 at 03:00PM",
        confirmedAt: "1 August 2024 at 03:45PM",
        paymentStatus: "Completed",
        items: sampleOrderItems,
    },
    {
        id: "10",
        orderNumber: "RE-2026-7895",
        customerName: "Club DNA",
        customerEmail: "dna@lagosclubs.ng",
        customerPhone: "070 8899 0011",
        deliveryAddress: "Adetokunbo Ademola St, Victoria Island, Lagos",
        amount: 1850000,
        subtotal: 1850000,
        deliveryFee: 0,
        progress: "Order Confirmed",
        category: "ongoing",
        date: "2nd August, 2024",
        placedAt: "2 August 2024 at 06:30PM",
        confirmedAt: "2 August 2024 at 07:15PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[1], sampleOrderItems[2]],
    },

    // Completed Orders (Screenshot 1)
    {
        id: "comp-1",
        orderNumber: "RE-2026-7890",
        customerName: "John Amadi",
        customerEmail: "J.amadi1@gmail.com",
        customerPhone: "091 2345 6789",
        deliveryAddress: "16 Pinnock Beach Rd, Lekki Phase 1, Lagos",
        amount: 75000,
        subtotal: 75000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "25th July, 2024",
        placedAt: "29 July 2026 at 10:42PM",
        confirmedAt: "29 July 2026 at 10:42PM",
        inTransitAt: "29 July 2026 at 10:42PM",
        deliveredAt: "29 July 2026 at 11:12PM",
        paymentStatus: "Completed",
        items: sampleOrderItems,
    },
    {
        id: "comp-2",
        orderNumber: "RE-2026-7892",
        customerName: "Quilox Ent",
        customerEmail: "vip@quilox.ng",
        customerPhone: "080 9999 1234",
        deliveryAddress: "Ozumba Mbadiwe Ave, Victoria Island, Lagos",
        amount: 3125000,
        subtotal: 3125000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "26th July, 2024",
        placedAt: "26 July 2024 at 02:15PM",
        confirmedAt: "26 July 2024 at 03:00PM",
        inTransitAt: "26 July 2024 at 04:30PM",
        deliveredAt: "26 July 2024 at 06:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[1]],
    },
    {
        id: "comp-3",
        orderNumber: "RE-2026-7891",
        customerName: "Castiel Dean",
        customerEmail: "castiel@winchester.com",
        customerPhone: "081 2233 4455",
        deliveryAddress: "Banana Island, Ikoyi, Lagos",
        amount: 120000,
        subtotal: 120000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "27th July, 2024",
        placedAt: "27 July 2024 at 11:20AM",
        confirmedAt: "27 July 2024 at 12:05PM",
        inTransitAt: "27 July 2024 at 01:30PM",
        deliveredAt: "27 July 2024 at 03:15PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0]],
    },
    {
        id: "comp-4",
        orderNumber: "RE-2026-7890",
        customerName: "Castle Lounge",
        customerEmail: "reservations@castlelounge.com",
        customerPhone: "070 3344 5566",
        deliveryAddress: "Admiralty Way, Lekki Phase 1, Lagos",
        amount: 5000000,
        subtotal: 5000000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "25th July, 2024",
        placedAt: "25 July 2024 at 09:30AM",
        confirmedAt: "25 July 2024 at 10:15AM",
        inTransitAt: "25 July 2024 at 01:00PM",
        deliveredAt: "25 July 2024 at 04:00PM",
        paymentStatus: "Completed",
        items: sampleOrderItems,
    },
    {
        id: "comp-5",
        orderNumber: "RE-2026-7893",
        customerName: "Sunflower Bar",
        customerEmail: "orders@sunflowerbar.ng",
        customerPhone: "080 5566 7788",
        deliveryAddress: "Bourdillon Rd, Ikoyi, Lagos",
        amount: 1225000,
        subtotal: 1225000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "28th July, 2024",
        placedAt: "28 July 2024 at 01:10PM",
        confirmedAt: "28 July 2024 at 02:00PM",
        inTransitAt: "28 July 2024 at 03:30PM",
        deliveredAt: "28 July 2024 at 05:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[2]],
    },
    {
        id: "comp-6",
        orderNumber: "RE-2026-7897",
        customerName: "Daisy Dine",
        customerEmail: "chef@daisydine.ng",
        customerPhone: "090 1122 3344",
        deliveryAddress: "Adeola Odeku St, Victoria Island, Lagos",
        amount: 1350000,
        subtotal: 1350000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "29th July, 2024",
        placedAt: "29 July 2024 at 11:00AM",
        confirmedAt: "29 July 2024 at 11:45AM",
        inTransitAt: "29 July 2024 at 02:30PM",
        deliveredAt: "29 July 2024 at 04:15PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0], sampleOrderItems[2]],
    },
    {
        id: "comp-7",
        orderNumber: "RE-2026-7893",
        customerName: "Sunflower Bar",
        customerEmail: "orders@sunflowerbar.ng",
        customerPhone: "080 5566 7788",
        deliveryAddress: "Bourdillon Rd, Ikoyi, Lagos",
        amount: 1475000,
        subtotal: 1475000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "30th July, 2024",
        placedAt: "30 July 2024 at 04:15PM",
        confirmedAt: "30 July 2024 at 05:00PM",
        inTransitAt: "30 July 2024 at 06:15PM",
        deliveredAt: "30 July 2024 at 07:30PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[1]],
    },
    {
        id: "comp-8",
        orderNumber: "RE-2026-7896",
        customerName: "Rosemary Bistro",
        customerEmail: "bar@rosemarybistro.com",
        customerPhone: "081 7788 9900",
        deliveryAddress: "Sanusi Fafunwa St, Victoria Island, Lagos",
        amount: 1600000,
        subtotal: 1600000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "31st July, 2024",
        placedAt: "31 July 2024 at 10:00AM",
        confirmedAt: "31 July 2024 at 10:45AM",
        inTransitAt: "31 July 2024 at 01:20PM",
        deliveredAt: "31 July 2024 at 03:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0], sampleOrderItems[1]],
    },
    {
        id: "comp-9",
        orderNumber: "RE-2026-7894",
        customerName: "Lavender Lounge",
        customerEmail: "manager@lavenderlounge.ng",
        customerPhone: "080 6677 8899",
        deliveryAddress: "Bisola Durosinmi Etti Dr, Lekki Phase 1, Lagos",
        amount: 1725000,
        subtotal: 1725000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "1st August, 2024",
        placedAt: "1 August 2024 at 03:00PM",
        confirmedAt: "1 August 2024 at 03:45PM",
        inTransitAt: "1 August 2024 at 05:15PM",
        deliveredAt: "1 August 2024 at 06:45PM",
        paymentStatus: "Completed",
        items: sampleOrderItems,
    },
    {
        id: "comp-10",
        orderNumber: "RE-2026-7895",
        customerName: "Club DNA",
        customerEmail: "dna@lagosclubs.ng",
        customerPhone: "070 8899 0011",
        deliveryAddress: "Adetokunbo Ademola St, Victoria Island, Lagos",
        amount: 1850000,
        subtotal: 1850000,
        deliveryFee: 0,
        progress: "Delivered",
        category: "completed",
        date: "2nd August, 2024",
        placedAt: "2 August 2024 at 06:30PM",
        confirmedAt: "2 August 2024 at 07:15PM",
        inTransitAt: "2 August 2024 at 08:30PM",
        deliveredAt: "2 August 2024 at 10:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[1], sampleOrderItems[2]],
    },

    // Failed Orders (Screenshot 3)
    {
        id: "fail-1",
        orderNumber: "RE-2026-7890",
        customerName: "John Amadi",
        customerEmail: "J.amadi1@gmail.com",
        customerPhone: "091 2345 6789",
        deliveryAddress: "16 Pinnock Beach Rd, Lekki Phase 1, Lagos",
        amount: 75000,
        subtotal: 75000,
        deliveryFee: 0,
        progress: "Failed",
        category: "failed",
        date: "25th July, 2024",
        placedAt: "29 July 2026 at 10:42PM",
        confirmedAt: "29 July 2026 at 10:42PM",
        inTransitAt: "29 July 2026 at 10:42PM",
        failedAt: "29 July 2026 at 11:12PM",
        paymentStatus: "Completed",
        items: sampleOrderItems,
    },
    {
        id: "fail-2",
        orderNumber: "RE-2026-7892",
        customerName: "Quilox Ent",
        customerEmail: "vip@quilox.ng",
        customerPhone: "080 9999 1234",
        deliveryAddress: "Ozumba Mbadiwe Ave, Victoria Island, Lagos",
        amount: 3125000,
        subtotal: 3125000,
        deliveryFee: 0,
        progress: "Failed",
        category: "failed",
        date: "26th July, 2024",
        placedAt: "26 July 2024 at 02:15PM",
        confirmedAt: "26 July 2024 at 03:00PM",
        inTransitAt: "26 July 2024 at 04:30PM",
        failedAt: "26 July 2024 at 06:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[1]],
    },
    {
        id: "fail-3",
        orderNumber: "RE-2026-7891",
        customerName: "Castiel Dean",
        customerEmail: "castiel@winchester.com",
        customerPhone: "081 2233 4455",
        deliveryAddress: "Banana Island, Ikoyi, Lagos",
        amount: 120000,
        subtotal: 120000,
        deliveryFee: 0,
        progress: "Failed",
        category: "failed",
        date: "27th July, 2024",
        placedAt: "27 July 2024 at 11:20AM",
        confirmedAt: "27 July 2024 at 12:05PM",
        inTransitAt: "27 July 2024 at 01:30PM",
        failedAt: "27 July 2024 at 03:15PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0]],
    },
    {
        id: "fail-4",
        orderNumber: "RE-2026-7890",
        customerName: "Castle Lounge",
        customerEmail: "reservations@castlelounge.com",
        customerPhone: "070 3344 5566",
        deliveryAddress: "Admiralty Way, Lekki Phase 1, Lagos",
        amount: 5000000,
        subtotal: 5000000,
        deliveryFee: 0,
        progress: "Failed",
        category: "failed",
        date: "25th July, 2024",
        placedAt: "25 July 2024 at 09:30AM",
        confirmedAt: "25 July 2024 at 10:15AM",
        inTransitAt: "25 July 2024 at 01:00PM",
        failedAt: "25 July 2024 at 04:00PM",
        paymentStatus: "Completed",
        items: sampleOrderItems,
    },
    {
        id: "fail-5",
        orderNumber: "RE-2026-7893",
        customerName: "Sunflower Bar",
        customerEmail: "orders@sunflowerbar.ng",
        customerPhone: "080 5566 7788",
        deliveryAddress: "Bourdillon Rd, Ikoyi, Lagos",
        amount: 1225000,
        subtotal: 1225000,
        deliveryFee: 0,
        progress: "Failed",
        category: "failed",
        date: "28th July, 2024",
        placedAt: "28 July 2024 at 01:10PM",
        confirmedAt: "28 July 2024 at 02:00PM",
        inTransitAt: "28 July 2024 at 03:30PM",
        failedAt: "28 July 2024 at 05:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[2]],
    },
    {
        id: "fail-6",
        orderNumber: "RE-2026-7897",
        customerName: "Daisy Dine",
        customerEmail: "chef@daisydine.ng",
        customerPhone: "090 1122 3344",
        deliveryAddress: "Adeola Odeku St, Victoria Island, Lagos",
        amount: 1350000,
        subtotal: 1350000,
        deliveryFee: 0,
        progress: "Failed",
        category: "failed",
        date: "29th July, 2024",
        placedAt: "29 July 2024 at 11:00AM",
        confirmedAt: "29 July 2024 at 11:45AM",
        inTransitAt: "29 July 2024 at 02:30PM",
        failedAt: "29 July 2024 at 04:15PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0], sampleOrderItems[2]],
    },
    {
        id: "fail-7",
        orderNumber: "RE-2026-7893",
        customerName: "Sunflower Bar",
        customerEmail: "orders@sunflowerbar.ng",
        customerPhone: "080 5566 7788",
        deliveryAddress: "Bourdillon Rd, Ikoyi, Lagos",
        amount: 1475000,
        subtotal: 1475000,
        deliveryFee: 0,
        progress: "Failed",
        category: "failed",
        date: "30th July, 2024",
        placedAt: "30 July 2024 at 04:15PM",
        confirmedAt: "30 July 2024 at 05:00PM",
        inTransitAt: "30 July 2024 at 06:15PM",
        failedAt: "30 July 2024 at 07:30PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[1]],
    },
    {
        id: "fail-8",
        orderNumber: "RE-2026-7896",
        customerName: "Rosemary Bistro",
        customerEmail: "bar@rosemarybistro.com",
        customerPhone: "081 7788 9900",
        deliveryAddress: "Sanusi Fafunwa St, Victoria Island, Lagos",
        amount: 1600000,
        subtotal: 1600000,
        deliveryFee: 0,
        progress: "Failed",
        category: "failed",
        date: "31st July, 2024",
        placedAt: "31 July 2024 at 10:00AM",
        confirmedAt: "31 July 2024 at 10:45AM",
        inTransitAt: "31 July 2024 at 01:20PM",
        failedAt: "31 July 2024 at 03:00PM",
        paymentStatus: "Completed",
        items: [sampleOrderItems[0], sampleOrderItems[1]],
    },
];

// In-memory / storage backed store
let ordersStore: OrderRecord[] = [...initialOrdersList];
const listeners = new Set<() => void>();

export const getOrders = (): OrderRecord[] => ordersStore;

export const getOrderByIdOrNumber = (
    idOrNumber: string,
): OrderRecord | undefined => {
    return (
        ordersStore.find(
            (o) =>
                o.id === idOrNumber ||
                o.orderNumber === idOrNumber ||
                `Order ${o.orderNumber}` === idOrNumber,
        ) || ordersStore[0]
    );
};

export const updateOrderStatus = (
    orderId: string,
    newProgress: OrderProgressStatus,
): OrderRecord | undefined => {
    const now = "29 July 2026 at 10:42PM";
    ordersStore = ordersStore.map((o) => {
        if (o.id === orderId || o.orderNumber === orderId) {
            let category: OrderCategory = "ongoing";
            const updated = { ...o, progress: newProgress };
            if (newProgress === "Order Confirmed") {
                updated.confirmedAt = now;
            } else if (newProgress === "InTransit") {
                updated.inTransitAt = now;
            } else if (newProgress === "Delivered") {
                updated.deliveredAt = "29 July 2026 at 11:12PM";
                category = "completed";
            } else if (newProgress === "Failed") {
                updated.failedAt = now;
                category = "failed";
            }
            updated.category = category;
            return updated;
        }
        return o;
    });
    listeners.forEach((l) => l());
    return getOrderByIdOrNumber(orderId);
};

export const subscribeOrders = (listener: () => void) => {
    listeners.add(listener);
    return () => {
        listeners.delete(listener);
    };
};
